### ISSUE TITLE
Proposal of a roadmap towards a v1 release

### ISSUE THREAD

**Issue by jenkin** [yohanboniface/geocodejson-spec#26]
No fundamental changes in draft spec.

- [ ] rename `draft` folder to `v1`
- [ ] update revision from `0.1` to `1.0`
- [ ] fix copyright notice (CC0 is public domain, not attribution)
- [ ] remove all `default: null` (optional attributes can be simply omitted)
- [ ] add examples for all attributes (ie. no `"district": null`)
- [ ] remove all `TODO` notices
- [ ] refactor spec text taking inspiration from [RFC7946](https://datatracker.ietf.org/doc/html/rfc7946) (GeoJSON spec)
- [ ] build an `index.html` file from spec md file (served as homepage, ie. using [markdown-to-html-cli](https://www.npmjs.com/package/markdown-to-html-cli))
- [ ] add JSON Schema with checksum #24
- [ ] build an interactive page to navigate spec schema (ie. using [@stoplight/json-schema-viewer](https://www.npmjs.com/package/@stoplight/json-schema-viewer))
- [ ] enable github pages to serve static content
- [ ] add a changelog
- [ ] add a code of conduct
- [ ] add contributing guidelines
- [ ] add a LICENSE file
- [ ] enrich README in root folder
- [ ] define issue templates: proposal, bug, q&a, use case report
- [ ] close all open issues
